name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  GO_VERSION: '^1.18.3'

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: License check
        run: |
          make license_check

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: |
          make lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Tests + coverage
        run: |
          make coverage

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build (all platforms)
        run: |
          make build_all_platforms
